name: "Lint"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

permissions: {}

jobs:
  ruff:
    name: "Ruff"
    runs-on: "ubuntu-latest"
    steps:
        - name: "Checkout the repository"
          uses: "actions/checkout@master"

        - name: "Set up Python"
          uses: actions/setup-python@master
          with:
            python-version: "3.14.5"

        - name: "Install requirements"
          run: python3 -m pip install .[dev]

